version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore MaikeBing.EntityFrameworkCore.NoSqLiteDB.sln
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
test: off
artifacts:
- path: MaikeBing.EntityFrameworkCore.NoSqLiteDB\bin\Release\MaikeBing.EntityFrameworkCore.NoSqLiteDB.*.nupkg
  name: MaikeBing.EntityFrameworkCore.NoSqLiteDB
